# permissions for end users to edit omahas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: omaha-editor-role
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - omahas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - omahas/status
  verbs:
  - get
