apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: helmchart-git-sample
spec:
  chart: charts/podinfo
  sourceRef:
    kind: GitRepository
    name: gitrepository-sample
  interval: 1m
