kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        service-account-jwks-uri: "https://kubernetes.default.svc.cluster.local/openid/v1/jwks"
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5555"]
    endpoint = ["http://sigstore-test-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."sigstore-test-registry:5000"]
    endpoint = ["http://sigstore-test-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5557"]
    endpoint = ["http://sigstore-test-registry2:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."sigstore-test-registry2:5000"]
    endpoint = ["http://sigstore-test-registry2:5000"]
